name: Build and Publish Docker image

on:
  workflow_dispatch:  # Allows manual trigger
  schedule:
    - cron: '0 2 1 * *'  # Scheduled to run at 02:00 AM UTC on the first of each month
    
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: leolele99/smtp2http:latest

    - name: Cleanup
      uses: docker/build-push-action@v3
      with:
        cleanup: true
